---
title: "comparison"
author: "NA"
date: "12/06/2016"
output: html_document
---

```{r}
fuzzy_makro_gl2 = "Fuzzylandform_res150m_ls3_hs21_R11000_R2714"
fuzzy_makro_gl1 = "Fuzzylandform_res150m_ls6_hs12_R19803_R2333"
fuzzy_meso_gl2 = "Fuzzylandform_res50m_ls15_hs21_R15000_R2500"
fuzzy_meso_gl1 = "Fuzzylandform_res50m_ls3_hs21_R1250_R2166"
dikau_makro_gl1 = "curv_landform_res100m_t600"
dikau_makro_gl2= "curv_landform_res100m_t600"
dikau_meso_gl1 = "curv_landform_res50m_t700"
dikau_meso_gl2 = "curv_landform_res50m_t300"
geom_makro_gl1 = "geom_DTM_50m_avg_fl10_L400m"
geom_makro_gl2= "geom_DTM_50m_avg_fl10_L400m"
geom_meso_gl1 = "geom_10m_fl8_L8"
geom_meso_gl2 = "geom_10m_fl8_L15"
wood_makro_gl1 = "feature_DTM_50m_avg_ws5_ts14_tc0p002000"
wood_makro_gl2= "feature_DTM_50m_avg_ws5_ts14_tc0p002000"
wood_meso_gl1 = "feature_DTM_SouthTyrol_10m_ws11_ts11_tc0p006000"
wood_meso_gl2 = "feature_DTM_SouthTyrol_10m_ws15_ts15_tc0p004000"
tpiLF_makro_gl1 =  "TPI_landforms_r70R250_10m"
tpiLF_makro_gl2 = "TPI_landforms_r150R700"
tpiLF_makro_gl2plus = c("TPI_landforms_r150R700","TPI_landforms_r50R200")
tpiLF_meso_gl1 = "TPI_landforms_r90R50_10m"
tpiLF_meso_gl2 = "TPI_landforms_r80R300_10m"
terrain_makro_gl1=c("Topographic_Wetness_Index","profc_DTM_50m_avg_ws7","minic_DTM_50m_avg_ws5")
terrain_makro_gl2 = c("Topographic_Wetness_Index","profc_DTM_50m_avg_ws7","minic_DTM_50m_avg_ws5")
terrain_meso_gl1 = c("TPI_i0m_o70m_10m","slope_DTM_50m_avg_ws3")
terrain_meso_gl2 = c("TPI_i0m_o90m_10m","Slope")
#iwapike_makro_gl1=c("iwapike_res100m_r1_n8") 
iwapike_makro_gl1=c("landforms_Conrad_10cells_12classes")   #res50m
iwapike_makro_gl2 = c("landforms_Conrad_7cells_12classes")   #res50m
iwapike_meso_gl1 = c("iwapike_r2_n8")  #res10m
iwapike_meso_gl2 = c("iwapike_r2_n12")  #res10m

source("/home/fabs/Data/paper1_lenny/fabians_and_rossiters_functions.R")
source("/home/fabs/Data/paper1_lenny/evaluateforwardselection_dev.R")
setwd("/home/fabs/Data/paper1_lenny/")
load("/home/fabs/Data/paper1_lenny/neu_unzugeordnet/landformlegends.RData")
load("/home/fabs/Data/paper1_lenny/neu_unzugeordnet/FWCV/makroreddata_andpredlists.RData")
relief_defredmak <- makroreddata[c("Def_red_mak","AufID")]
defredmak_ID <- makroreddata$AufID
load("/home/fabs/Data/paper1_lenny/neu_unzugeordnet/FWCV/mesoreddata_andpredlists.RData")
relief_defredmes <- mesoreddata[c("Def_red_mes","AufID")]
defredmes_ID <- mesoreddata$AufID
load("/home/fabs/Data/paper1_lenny/neu_unzugeordnet/FWCV/makrodata_andpredlists.RData")
relief_ezclass <- makrodata[c("EZ_class","AufID")]
ezclass_ID <-makrodata$AufID
load("/home/fabs/Data/paper1_lenny/neu_unzugeordnet/FWCV/mesodata_andpredlists.RData")
relief_ezclassmes <- mesodata[c("EZ_class_mes","AufID")]
ezclassmes_ID <-mesodata$AufID
load("/home/fabs/Data/paper1_lenny/neu_unzugeordnet/FWCV/fuzzydata.RData")
fuzzy <- merge(x=fuzzy10m,relief_defredmak,by="AufID",all.x=T)
fuzzy <- merge(x=fuzzy,relief_defredmes,by="AufID",all.x=T)
fuzzy <- merge(x=fuzzy,relief_ezclass,by="AufID",all.x=T)
fuzzy <- merge(x=fuzzy,relief_ezclassmes,by="AufID",all.x=T)
###########ACHTUNG!!!
fuzzy_defredmes <- fuzzy[fuzzy$AufID %in% defredmes_ID,c("AufID",fuzzy_meso_gl1,"Def_red_mes")]
fuzzy_defredmak <- fuzzy[fuzzy$AufID %in% defredmak_ID,c("AufID",fuzzy_makro_gl1,"Def_red_mak")]
fuzzy_ezclass <- fuzzy[fuzzy$AufID %in% ezclass_ID,c("AufID",fuzzy_makro_gl2,"EZ_class")]
fuzzy_ezclassmes <- fuzzy[fuzzy$AufID %in% ezclassmes_ID,c("AufID",fuzzy_meso_gl2,"EZ_class_mes")]
rm(fuzzy10m)
rm(fuzzy)

geom_defredmes <- mesoreddata[mesoreddata$AufID %in% defredmes_ID,c("AufID","geom_10m_fl8_L8","Def_red_mes")]
geom_defredmak <- makroreddata[makroreddata$AufID %in% defredmak_ID,c("AufID","geom_DTM_50m_avg_fl10_L400m","Def_red_mak")]
geom_ezclass <- makrodata[makrodata$AufID %in% ezclass_ID,c("AufID","geom_DTM_50m_avg_fl10_L400m","EZ_class")]
geom_ezclassmes <- mesodata[mesodata$AufID %in% ezclassmes_ID,c("AufID","geom_10m_fl8_L15","EZ_class_mes")]
#########################
load("/home/fabs/Data/paper1_lenny/neu_unzugeordnet/FWCV/modeldata_ezclass_dikau.RData")
dikau_ezclass <- modeldata_ezclass_dikau[modeldata_ezclass_dikau$AufID %in% ezclass_ID,c("AufID","curv_landform_res100m_t600","EZ_class")]
dikau_ezclass$curv_landform_res100m_t600 <- as.factor(dikau_ezclass$curv_landform_res100m_t600)
rm(modeldata_ezclass_dikau)
load("/home/fabs/Data/paper1_lenny/neu_unzugeordnet/FWCV/modeldata_ezclassmes_dikau.RData")
dikau_ezclassmes <- modeldata_ezclassmes_dikau[modeldata_ezclassmes_dikau$AufID %in% ezclassmes_ID,c("AufID","curv_landform_res50m_t300","EZ_class_mes")]
dikau_ezclassmes$curv_landform_res50m_t300 <- as.factor(dikau_ezclassmes$curv_landform_res50m_t300)
rm(modeldata_ezclassmes_dikau)
load("/home/fabs/Data/paper1_lenny/neu_unzugeordnet/FWCV/modeldata_makrored_dikau.RData")
dikau_defredmak <- modeldata_makrored_dikau[modeldata_makrored_dikau$AufID %in% defredmak_ID,c("AufID","curv_landform_res100m_t600","Def_red_mak")]
dikau_defredmak$curv_landform_res100m_t600 <- as.factor(dikau_defredmak$curv_landform_res100m_t600)
rm(modeldata_makrored_dikau)
load("/home/fabs/Data/paper1_lenny/neu_unzugeordnet/FWCV/modeldata_mesored_dikau.RData")
dikau_defredmes <- modeldata_mesored_dikau[modeldata_mesored_dikau$AufID %in% defredmes_ID,c("AufID","curv_landform_res50m_t700","Def_red_mes")]
dikau_defredmes$curv_landform_res50m_t700 <- as.factor(dikau_defredmes$curv_landform_res50m_t700)
rm(modeldata_mesored_dikau)
###################################wooddata 
  load("/home/fabs/Data/paper1_lenny/neu_unzugeordnet/FWCV/modeldata_mesoreddata_wood_withAufID.RData")
wood_defredmes<-modeldata_mesoreddata_wood[modeldata_mesoreddata_wood$AufID %in% defredmes_ID,c("AufID","feature_DTM_SouthTyrol_10m_ws11_ts11_tc0p006000","Def_red_mes")]
rm(modeldata_mesoreddata_wood)
  load("/home/fabs/Data/paper1_lenny/neu_unzugeordnet/FWCV/modeldata_makroreddata_wood_withAufID.RData")
wood_defredmak<-modeldata_makroreddata_wood[modeldata_makroreddata_wood$AufID %in% defredmak_ID,c("AufID","feature_DTM_50m_avg_ws5_ts14_tc0p002000","Def_red_mak")]
str(wood_defredmak)
rm(modeldata_makroreddata_wood)
  load("/home/fabs/Data/paper1_lenny/neu_unzugeordnet/FWCV/modeldata_makrodata_wood_withAufID.RData")
wood_ezclass<-modeldata_makrodata_wood[modeldata_makrodata_wood$AufID %in% ezclass_ID,c("AufID","feature_DTM_50m_avg_ws5_ts14_tc0p002000","EZ_class")]
str(wood_ezclass)
rm(modeldata_makrodata_wood)
  load("/home/fabs/Data/paper1_lenny/neu_unzugeordnet/FWCV/modeldata_mesodata_wood_withAufID.RData")
wood_ezclassmes<-modeldata_mesodata_wood[modeldata_mesodata_wood$AufID %in% ezclassmes_ID,c("AufID","feature_DTM_SouthTyrol_10m_ws15_ts15_tc0p004000","EZ_class_mes")]
str(wood_ezclassmes)
rm(modeldata_mesodata_wood)
######################################################
###TPILANDFORMS
tpiLF_defredmes <- mesoreddata[mesoreddata$AufID %in% defredmes_ID,c("AufID",tpiLF_meso_gl1,"Def_red_mes")]
tpiLF_defredmak <- makroreddata[makroreddata$AufID %in% defredmak_ID,c("AufID",tpiLF_makro_gl1,"Def_red_mak")]
tpiLF_ezclass <- makrodata[makrodata$AufID %in% ezclass_ID,c("AufID",tpiLF_makro_gl2,"EZ_class")]
tpiLF_ezclassmes <- mesodata[mesodata$AufID %in% ezclassmes_ID,c("AufID",tpiLF_meso_gl2,"EZ_class_mes")]
###########################################
#TERRAIN COLS
terrain_defredmes <- mesoreddata[mesoreddata$AufID %in% defredmes_ID,c("AufID",terrain_meso_gl1,"Def_red_mes")]
terrain_defredmak <- makroreddata[makroreddata$AufID %in% defredmak_ID,c("AufID",terrain_makro_gl1,"Def_red_mak")]
terrain_ezclass <- makrodata[makrodata$AufID %in% ezclass_ID,c("AufID",terrain_makro_gl2,"EZ_class")]
terrain_ezclassmes <- mesodata[mesodata$AufID %in% ezclassmes_ID,c("AufID",terrain_meso_gl2,"EZ_class_mes")]
###########################################
#IWAPIKE COLS
load("/home/fabs/Data/paper1_lenny/results_iwapike/modeldata_iwapike.RData")
iwapike_defredmes <- modeldata_defredmes_iwapike[modeldata_defredmes_iwapike$AufID %in% defredmes_ID,c("AufID",iwapike_meso_gl1,"Def_red_mes")]
iwapike_defredmak <- modeldata_defredmak_iwapike[modeldata_defredmak_iwapike$AufID %in% defredmak_ID,c("AufID",iwapike_makro_gl1,"Def_red_mak")]
iwapike_ezclass <- modeldata_ezclass_iwapike[modeldata_ezclass_iwapike$AufID %in% ezclass_ID,c("AufID",iwapike_makro_gl2,"EZ_class")]
iwapike_ezclassmes <- modeldata_ezclassmes_iwapike[modeldata_ezclassmes_iwapike$AufID %in% ezclassmes_ID,c("AufID",iwapike_meso_gl2,"EZ_class_mes")]
#######################################
#make topolegends
load("/home/fabs/Data/paper1_lenny/neu_unzugeordnet/FWCV/allmodeldataforSVM.RData")
#######################################
redmak_old <- levels(makrodata_red$Def_red_mak)
redmak <- redmak_old[c(1,6,5,7,2,3,4)]
makrogeneralized1 <- c("FL","LO","DA","FS","BS","SH","RI")
makrolegend_gen1 <- data.frame(makrogeneralized1)
makrolegend_gen1$Def_red_mak <-  factor(redmak, levels=redmak_old[c(1,6,5,7,2,3,4)])
makrolegend_gen1$makrogeneralized1 <- factor(makrogeneralized1,levels=c("FL","LO","DA","FS","BS","SH","RI")) 
makrolegend_gen1$code<- 1:nrow(makrolegend_gen1)
str(makrolegend_gen1)
makrolegend_gen1
ezclass<- levels(EZclassdata$EZ_class)
ezclass <- ezclass[c(2,1,3,4)]
makrogeneralized2 <- c("CH","FS","BS","SH")
makrolegend_gen2 <- data.frame(makrogeneralized2)
makrolegend_gen2$EZ_class  <-factor(ezclass,levels=c("gulley","footslope","hillslope","shoulder")) 
makrolegend_gen2$makrogeneralized2 <- factor(makrogeneralized2,levels=c("CH","FS","BS","SH"))
makrolegend_gen2$code<- 1:nrow(makrolegend_gen2)
str(makrolegend_gen2)
makrolegend_gen2
############################################################################
mesored <- levels(mesodata_red$Def_red_mes)
mesored <- mesored[c(1,8,7,9,2,4,3,5,6)]
mesogeneralized1 <-c("FL","LO","DA","FS","SF","BS","SS","SH","RI")
mesolegend_gen1 <- data.frame(mesogeneralized1)
mesolegend_gen1$Def_red_mes <-  factor(mesored, levels=c("Eben","Tief","Schwemmschutt","Unterhang","HVF", "Mittelhang","HVS","Oberhang","Ruecken"))
mesolegend_gen1$mesogeneralized1 <- factor(mesogeneralized1,levels=c("FL","LO","DA","FS","SF","BS","SS","SH","RI")) 
mesolegend_gen1$code<- 1:nrow(mesolegend_gen1)
str(mesolegend_gen1)
mesolegend_gen1
####################################
############################################################################
ezclassmes <- levels(EZclassmesdata$EZ_class_mes)
mesogeneralized2 <-c("FS","BS","SH")
mesolegend_gen2 <- data.frame(mesogeneralized2)
mesolegend_gen2$EZ_class_mes <-  factor(ezclassmes, levels=c("footslope","hillslope","shoulder"))
mesolegend_gen2$mesogeneralized2 <- factor(mesogeneralized2,levels=c("FS","BS","SH")) 
mesolegend_gen2$code<- 1:nrow(mesolegend_gen2)
str(mesolegend_gen2)
mesolegend_gen2
####################################
source("/home/fabs/Data/paper1_lenny/fabians_and_rossiters_functions.R")
```

```{r}
#predict_radial_newlegend_newmap <- function(modeldata,newdata,dependent,predictors,legend,doreturn=FALSE,outname)#

predict_radial_newlegend_newmap(modeldata=fuzzy_defredmak,dependent="Def_red_mak",predictors=fuzzy_makro_gl1,legend=makrolegend_gen1,input="/home/fabs/Data/paper1_lenny/GIS/paper_10m_comparisons_aoijan2/Fuzzylandforms_macro_GL1_6t012deg_R9803_R333_from150m.tif",outname="fuzzy")
#fuzzy_defredmak$preds <- predict_radial_newlegend(modeldata=fuzzy_defredmak,dependent="Def_red_mak",predictors=fuzzy_makro_gl1,legend=makrolegend_gen1)
predict_radial_newlegend_newmap(modeldata=fuzzy_ezclass,dependent="EZ_class",predictors=fuzzy_makro_gl2,legend=makrolegend_gen2,input="/home/fabs/Data/paper1_lenny/GIS/paper_10m_comparisons_aoijan2/Fuzzylandforms_macro_GL2_3to21deg_R1000_R714_from150m.tif",outname="fuzzy")
#fuzzy_ezclass$preds <- predict_radial_newlegend(modeldata=fuzzy_ezclass,dependent="EZ_class",predictors=fuzzy_makro_gl2,legend=makrolegend_gen2)
predict_radial_newlegend_newmap(modeldata=fuzzy_defredmes,dependent="Def_red_mes",predictors=fuzzy_meso_gl1,legend=mesolegend_gen1,input="/home/fabs/Data/paper1_lenny/GIS/paper_10m_comparisons_aoijan2/Fuzzylandforms_meso_GL1_3to21deg_R250_R166_from50m.tif",outname="fuzzy")
#fuzzy_defredmes$preds <- predict_radial_newlegend(modeldata=fuzzy_defredmes,dependent="Def_red_mes",predictors=fuzzy_meso_gl1,legend=mesolegend_gen1)
predict_radial_newlegend_newmap(modeldata=fuzzy_ezclassmes,dependent="EZ_class_mes",predictors=fuzzy_meso_gl2,legend=mesolegend_gen2,input="/home/fabs/Data/paper1_lenny/GIS/paper_10m_comparisons_aoijan2/Fuzzylandforms_meso_GL2_15to21deg_R5000_R500_from50m.tif",outname="fuzzy")
#fuzzy_ezclassmes$preds <- predict_radial_newlegend(modeldata=fuzzy_ezclassmes,dependent="EZ_class_mes",predictors=fuzzy_meso_gl2,legend=mesolegend_gen2)
##########################################
#dikau_defredmak$preds <- predict_radial_newlegend(modeldata=dikau_defredmak,dependent="Def_red_mak",predictors=dikau_makro_gl1,legend=makrolegend_gen1)
predict_radial_newlegend_newmap(modeldata=dikau_defredmak,dependent="Def_red_mak",predictors=dikau_makro_gl1,legend=makrolegend_gen1,input="/home/fabs/Data/paper1_lenny/GIS/paper_10m_comparisons_aoijan2/Curvatureclassification_res100m_t0p006_from100m.tif",outname="dikau")
#dikau_ezclass$preds <- predict_radial_newlegend(modeldata=dikau_ezclass,dependent="EZ_class",predictors=dikau_makro_gl2,legend=makrolegend_gen2)
predict_radial_newlegend_newmap(modeldata=dikau_ezclass,dependent="EZ_class",predictors=dikau_makro_gl2,legend=makrolegend_gen2,input="/home/fabs/Data/paper1_lenny/GIS/paper_10m_comparisons_aoijan2/Curvatureclassification_res100m_t0p006_from100m.tif",outname="dikau")
#dikau_defredmes$preds <- predict_radial_newlegend(modeldata=dikau_defredmes,dependent="Def_red_mes",predictors=dikau_meso_gl1,legend=mesolegend_gen1)
predict_radial_newlegend_newmap(modeldata=dikau_defredmes,dependent="Def_red_mes",predictors=dikau_meso_gl1,legend=mesolegend_gen1,input="/home/fabs/Data/paper1_lenny/GIS/paper_10m_comparisons_aoijan2/Curvatureclassification_res50m_t0p007_from50m.tif",outname="dikau")
#dikau_ezclassmes$preds <- predict_radial_newlegend(modeldata=dikau_ezclassmes,dependent="EZ_class_mes",predictors=dikau_meso_gl2,legend=mesolegend_gen2)
predict_radial_newlegend_newmap(modeldata=dikau_ezclassmes,dependent="EZ_class_mes",predictors=dikau_meso_gl2,legend=mesolegend_gen2,input="/home/fabs/Data/paper1_lenny/GIS/paper_10m_comparisons_aoijan2/Curvatureclassification_res50m_t0p003_from50m.tif",outname="dikau")
##########################################
predict_radial_newlegend_newmap(modeldata=wood_defredmak,dependent="Def_red_mak",predictors=wood_makro_gl1,legend=makrolegend_gen1,input="/home/fabs/Data/paper1_lenny/GIS/paper_10m_comparisons_aoijan2/wood_ws5_ts14_tc0p002_makro1_from50m.tif",outname="wood")
predict_radial_newlegend_newmap(modeldata=wood_ezclass,dependent="EZ_class",predictors=wood_makro_gl2,legend=makrolegend_gen2,input="/home/fabs/Data/paper1_lenny/GIS/paper_10m_comparisons_aoijan2/wood_ws5_ts14_tc0p002_makro1_from50m.tif",outname="wood")
predict_radial_newlegend_newmap(modeldata=wood_defredmes,dependent="Def_red_mes",predictors=wood_meso_gl1,legend=mesolegend_gen1,input="/home/fabs/Data/paper1_lenny/GIS/paper_10m_comparisons_aoijan2/wood_10m_ws110m_ts11_tc0p006_meso1.tif",outname="wood")
predict_radial_newlegend_newmap(modeldata=wood_ezclassmes,dependent="EZ_class_mes",predictors=wood_meso_gl2,legend=mesolegend_gen2,input="/home/fabs/Data/paper1_lenny/GIS/paper_10m_comparisons_aoijan2/wood_10m_ws150m_ts15_tc0p004_meso2.tif",outname="wood")
#wood_defredmak$preds <- predict_radial_newlegend(modeldata=wood_defredmak,dependent="Def_red_mak",predictors=wood_makro_gl1,legend=makrolegend_gen1)
#wood_ezclass$preds <- predict_radial_newlegend(modeldata=wood_ezclass,dependent="EZ_class",predictors=wood_makro_gl2,legend=makrolegend_gen2)
#wood_defredmes$preds <- predict_radial_newlegend(modeldata=wood_defredmes,dependent="Def_red_mes",predictors=wood_meso_gl1,legend=mesolegend_gen1)
#wood_ezclassmes$preds <- predict_radial_newlegend(modeldata=wood_ezclassmes,dependent="EZ_class_mes",predictors=wood_meso_gl2,legend=mesolegend_gen2)
##########################################
predict_radial_newlegend_newmap(modeldata=geom_defredmak,dependent="Def_red_mak",predictors=geom_makro_gl1,legend=makrolegend_gen1,input="/home/fabs/Data/paper1_lenny/GIS/paper_10m_comparisons_aoijan2/geom_50m_L400m_10deg_from50m.tif",outname="geom")
predict_radial_newlegend_newmap(modeldata=geom_ezclass,dependent="EZ_class",predictors=geom_makro_gl2,legend=makrolegend_gen2,input="/home/fabs/Data/paper1_lenny/GIS/paper_10m_comparisons_aoijan2/geom_50m_L400m_10deg_from50m.tif",outname="geom")
predict_radial_newlegend_newmap(modeldata=geom_defredmes,dependent="Def_red_mes",predictors=geom_meso_gl1,legend=mesolegend_gen1,input="/home/fabs/Data/paper1_lenny/GIS/paper_10m_comparisons_aoijan2/geom_10m_L80m_8deg.tif",outname="geom")
predict_radial_newlegend_newmap(modeldata=geom_ezclassmes,dependent="EZ_class_mes",predictors=geom_meso_gl2,legend=mesolegend_gen2,input="/home/fabs/Data/paper1_lenny/GIS/paper_10m_comparisons_aoijan2/geom_10m_L150m_8deg.tif",outname="geom")
#geom_defredmak$preds <- predict_radial_newlegend(modeldata=geom_defredmak,dependent="Def_red_mak",predictors=geom_makro_gl1,legend=makrolegend_gen1)
#geom_ezclass$preds <- predict_radial_newlegend(modeldata=geom_ezclass,dependent="EZ_class",predictors=geom_makro_gl2,legend=makrolegend_gen2)
#geom_defredmes$preds <- predict_radial_newlegend(modeldata=geom_defredmes,dependent="Def_red_mes",predictors=geom_meso_gl1,legend=mesolegend_gen1)
#geom_ezclassmes$preds <- predict_radial_newlegend(modeldata=geom_ezclassmes,dependent="EZ_class_mes",predictors=geom_meso_gl2,legend=mesolegend_gen2)
##########################################
##########################################
predict_radial_newlegend_newmap(modeldata=tpiLF_defredmak,dependent="Def_red_mak",predictors=tpiLF_makro_gl1,legend=makrolegend_gen1,input="/home/fabs/Data/paper1_lenny/GIS/paper_10m_comparisons_aoijan2/TPIlandforms_r70R250_10m.tif",outname="tpiLF")
predict_radial_newlegend_newmap(modeldata=tpiLF_ezclass,dependent="EZ_class",predictors=tpiLF_makro_gl2,legend=makrolegend_gen2,input="/home/fabs/Data/paper1_lenny/GIS/paper_10m_comparisons_aoijan2/TPIlandforms_r150R700_50m_from50m.tif",outname="tpiLF")
predict_radial_newlegend_newmap(modeldata=tpiLF_defredmes,dependent="Def_red_mes",predictors=tpiLF_meso_gl1,legend=mesolegend_gen1,input="/home/fabs/Data/paper1_lenny/GIS/paper_10m_comparisons_aoijan2/TPIlandforms_r90R50_10m.tif",outname="tpiLF")
predict_radial_newlegend_newmap(modeldata=tpiLF_ezclassmes,dependent="EZ_class_mes",predictors=tpiLF_meso_gl2,legend=mesolegend_gen2,input="/home/fabs/Data/paper1_lenny/GIS/paper_10m_comparisons_aoijan2/TPIlandforms_r80R300_10m.tif",outname="tpiLF")
#tpiLF_defredmak$preds <- predict_radial_newlegend(modeldata=tpiLF_defredmak,dependent="Def_red_mak",predictors=tpiLF_makro_gl1,legend=makrolegend_gen1)
#tpiLF_ezclass$preds <- predict_radial_newlegend(modeldata=tpiLF_ezclass,dependent="EZ_class",predictors=tpiLF_makro_gl2,legend=makrolegend_gen2)
#tpiLF_defredmes$preds <- predict_radial_newlegend(modeldata=tpiLF_defredmes,dependent="Def_red_mes",predictors=tpiLF_meso_gl1,legend=mesolegend_gen1)
#tpiLF_ezclassmes$preds <- predict_radial_newlegend(modeldata=tpiLF_ezclassmes,dependent="EZ_class_mes",predictors=tpiLF_meso_gl2,legend=mesolegend_gen2)
###########################################
##########################################
predict_radial_newlegend_newmap_multiprednumeric <- function(modeldata,dependent,predictors,legend,doreturn=FALSE,outname,input)
predict_radial_newlegend_newmap_multiprednumeric(modeldata=terrain_defredmak,dependent="Def_red_mak",predictors=terrain_makro_gl1,legend=makrolegend_gen1,input=list("/home/fabs/Data/paper1_lenny/GIS/paper_10m_comparisons_aoijan2/Topographic_Wetness_Index_50m.tif","/home/fabs/Data/paper1_lenny/GIS/paper_10m_comparisons_aoijan2/profc_50m_ws350m_from50m.tif","/home/fabs/Data/paper1_lenny/GIS/paper_10m_comparisons_aoijan2/minic_50m_ws250m_from50m.tif"),outname="terrain")
predict_radial_newlegend_newmap_multiprednumeric(modeldata=terrain_ezclass,dependent="EZ_class",predictors=terrain_makro_gl2,legend=makrolegend_gen2,input=list("/home/fabs/Data/paper1_lenny/GIS/paper_10m_comparisons_aoijan2/Topographic_Wetness_Index_50m.tif","/home/fabs/Data/paper1_lenny/GIS/paper_10m_comparisons_aoijan2/profc_50m_ws350m_from50m.tif","/home/fabs/Data/paper1_lenny/GIS/paper_10m_comparisons_aoijan2/minic_50m_ws250m_from50m.tif"),outname="terrain")
predict_radial_newlegend_newmap_multiprednumeric(modeldata=terrain_defredmes,dependent="Def_red_mes",predictors=terrain_meso_gl1,legend=mesolegend_gen1,input=list("/home/fabs/Data/paper1_lenny/GIS/paper_10m_comparisons_aoijan2/TPI_10m_R70m.tif","/home/fabs/Data/paper1_lenny/GIS/paper_10m_comparisons_aoijan2/slope_50m_ws150m.tif"),outname="terrain")
predict_radial_newlegend_newmap_multiprednumeric(modeldata=terrain_ezclassmes,dependent="EZ_class_mes",predictors=terrain_meso_gl2,legend=mesolegend_gen2,input=list("/home/fabs/Data/paper1_lenny/GIS/paper_10m_comparisons_aoijan2/TPI_10m_R90m.tif","/home/fabs/Data/paper1_lenny/GIS/paper_10m_comparisons_aoijan2/Slope_50m.tif"),outname="terrain")

#terrain_defredmak$preds <- predict_radial_newlegend(modeldata=terrain_defredmak,dependent="Def_red_mak",predictors=terrain_makro_gl1,legend=makrolegend_gen1)
#terrain_ezclass$preds <- predict_radial_newlegend(modeldata=terrain_ezclass,dependent="EZ_class",predictors=terrain_makro_gl2,legend=makrolegend_gen2)
#terrain_defredmes$preds <- predict_radial_newlegend(modeldata=terrain_defredmes,dependent="Def_red_mes",predictors=terrain_meso_gl1,legend=mesolegend_gen1)
#terrain_ezclassmes$preds <- predict_radial_newlegend(modeldata=terrain_ezclassmes,dependent="EZ_class_mes",predictors=terrain_meso_gl2,legend=mesolegend_gen2)
##########################################


```
